### ISSUE TITLE
how to handle success & failure situations BOTH simultaneously

### ISSUE THREAD

**Issue by pawarvijay** [express-promise-router/express-promise-router#55]
Kind of confusing, Need implementation help

```
exports.getContact = async function getContact (req, res, next) {
    try {
      const { rows } = await db.query('SELECT * FROM users WHERE id = $1', [req.id])
      res.send(rows[0]);  //success
    } catch (e) {
      return next(createError(401, 'Invalid Contact Id')) // failure
    }
};
```
The examples include two situations

**Success**  :` res.send(rows[0]);  `
during this _next()_ will be called and function will end

**Failure** : `return next(createError(401, 'Invalid Contact Id'))`
It will return an error to `next` middleware

In all examples / documentation only one situation is mentioned either `Promise.resolve` Or `Promise.reject`

**Note** :
I don't want to use `.then` as it gives rise to _callback hell_ 
I don't want to use `try/catch` as below post say we don't need to [link](http://cryto.net/~joepie91/blog/2015/05/14/using-promises-bluebird-with-express/)
 
**Question**: So how to handle **BOTH** success & failure situations with `express-promise-router` without `.then` & `try/catch `?

**Comment by mormahr** [comment]
Hi,

```js
router.get("/", function(req, res, next) {
    return db.query('SELECT * FROM users WHERE id = $1', [req.id])
        .then(function (result) {
            res.send(result)
        })
})
```

is equivalent to 

```js
router.get("/", async function(req, res, next) {
    const result = await db.query('SELECT * FROM users WHERE id = $1', [req.id])
    res.send(result)
})
```

a normal handler has to return the promise it used, but async functions automatically "generate" a promise, that includes all promises being awaited.
It is not necessary to catch errors produced by `db.query`, because awaiting it will automatically result in errors being propagated to the promise returned by the async function.

If you want to customize the generated error page, you can insert your own error handler at the end of the middleware chain.

I just write
```js
const router = ...

router.get("/contact", async function getContact (req, res, next) {
    const { rows } = await db.query('SELECT * FROM users WHERE id = $1', [req.id])
    res.send(rows[0]);  //success
});

router.use(function (err, req, res, next) { // <- These *have* to be 4 parameters
    res.status(500)
    res.send(err.toString()) // <- just an example, we have a mapping system and a custom view for errors
}) 
```
If you don't catch an error inside your request handler, promise-router will catch it and call next with it.



I hope this clears up some confusion, otherwise [ponyfoo's article](https://ponyfoo.com/articles/understanding-javascript-async-await) is a worthwhile read! Feel free to keep asking if something is unclear!


~Moritz
